'depth': 11
'min_density': 0.1
'n_threads': -1
'downsample': False
'voxel_size': 0.2
'max_nn': 20
'pc_range':  [0, -16, -2, 32, 16, 6]
'occ_size':  [160, 160, 40]
'self_range': [3.0, 3.0, 2.0]
'image_size': [1920, 1200]
